/*!
 * jQuery Cooltabs 1.0
 *    - http://cooltabs.codeserenity.com/
 *
 * Copyright 2010, Gilles Cochez
 * Dual licensed under the MIT and GPL licenses.
 *    - http://www.opensource.org/licenses/mit-license.php
 *    - http://www.gnu.org/copyleft/gpl.html
 */
(function(a){var b="content-wrap,wrap,left,middle,tab,tab-left,tab-middle,tab-right,right,arrow,clear".split(",");x=a.fn.cooltabs=function(c){c=a.extend({},a.fn.cooltabs.defaults,c);return this.each(function(){function k(a,b){var d=b?e.tab2:e.tab,h=b?e.tab2.children().eq(1):e.tab_middle,j=i.children().find("span");if(!b)i.children("li").each(function(){this.className=c.prefix+"inactive"});d.stop(!b).animate({left:a.position().left+10},{duration:c.speed,easing:c.tab_easing?c.tab_easing:"swing",step:function(){if(!b){var a={width:e.tab.innerWidth(),left:e.tab.position().left-20};j.each(function(b){if(f[b].left>=a.left-f[b].width&&f[b].left<=a.left+a.width)j.get(b).className=c.prefix+"on";else j.get(b).className=c.prefix+"off"})}},complete:function(){if(!b)a.get().className=c.prefix+"active"}});h.stop().animate({width:a.innerWidth()+"px"},{easing:c.tab_easing?c.tab_easing:"swing",duration:c.speed});if(!b)e.content_wrap.animate({left:"-"+a.attr("pos")*g+"px"},{easing:c.content_easing?c.content_easing:"swing",duration:c.speed})}var d=0,e={},f=[],g=0,h=0,i=a("<ul>"),j=a(this).children("div."+c.prefix+"content");a.each(b,function(d){e[b[d].replace("-","_")]=a("<div>").addClass(c.prefix+b[d])});e.tab2=e.tab.append(e.tab_left,e.tab_middle.append(e.arrow),e.tab_right,e.clear).clone().css("opacity",.2);e.wrap.append(e.left,e.middle.append(i,e.tab,e.tab2),e.right,e.clear).prependTo(this);j.each(function(b){a("<li>").attr("pos",b).html(function(){var b=j.children(c.header).eq(0).text().split(""),d="";a.each(b,function(a){d+="<span>"+b[a]+"</span>"});return d}).addClass(b>0?c.prefix+"inactive":c.prefix+"active").click(function(){k(a(this));this.className=c.prefix+"active"}).hover(function(){k(a(this),c.hover_fx)},function(){k(i.children("li."+c.prefix+"active").eq(0),c.hover_fx)}).appendTo(i).children("span").each(function(){f[d]={left:a(this).position().left,width:a(this).innerWidth()};d++});if(!h||a(this).innerHeight()>h)h=a(this).innerHeight();g=a(this).outerWidth();a(this).css({position:"absolute",width:g-20+"px",left:b*g,top:i.height()}).appendTo(e.content_wrap)});a(this).css("height",h+"px").children("."+c.prefix+"content").remove().end().append(e.content_wrap);e.tab_middle.css("width",i.children(0).innerWidth()+"px");})};a.fn.cooltabs.defaults={content_easing:"",tab_easing:"",prefix:"cooltabs-",hover_fx:true,header:"h3",speed:500}})(jQuery)